/**
 * @file use-auth-store.ts
 * @description Zustand store for fake authentication state.
 *
 * WHY ZUSTAND?
 * Zustand is a minimal, un-opinionated global state manager. Unlike Redux, it
 * requires zero boilerplate — you define your store as a plain function that
 * returns state + actions. The hook is auto-generated and can be consumed in
 * any component or even outside React (e.g., in the Axios interceptor).
 *
 * WHY "FAKE" AUTH?
 * JSONPlaceholder ignores any auth headers, but this pattern is critical for
 * real apps. The token lives in Zustand (not localStorage directly) so the
 * Axios interceptor can read it synchronously without any async overhead.
 *
 * ZUSTAND v5 NOTE:
 * In Zustand v5, `create` is imported directly from "zustand" (no sub-paths).
 * The store creator signature is the same as v4.
 */

import { create } from "zustand";

// type for zustand store we create (what data store saves)
interface AuthState {
  /** The bearer token that will be attached to every API request. */
  token: string | null;

  /** Action: simulates a user "logging in" by setting a token. */
  setToken: (token: string) => void;

  /** Action: simulates a user "logging out" by clearing the token. */
  clearToken: () => void;
}

/**
 * `useAuthStore` is a custom hook generated by Zustand.
 * Call it in any component:  `const token = useAuthStore(s => s.token)`
 * Call it outside React:     `useAuthStore.getState().token`
 *
 * The second pattern is used in our Axios interceptor to read the token
 * without needing React context, avoiding complex dependency injection.
 */
export const useAuthStore = create<AuthState>()((set) => ({
  // --- Initial State ---
  // Pre-populate with a dummy token so the interceptor has something to send
  // on every request from the moment the app loads.
  token: "dummy-jwt-token-abc123xyz",

  // --- Actions ---
  setToken: (token) => set({ token }),
  clearToken: () => set({ token: null }),
}));
